modLoader = "kotlinforforge"
loaderVersion = "[3.12.0,)"
issueTrackerURL = "https://github.com/SLimeyMC/${mod_id}/issues"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = ["SlimeyAr"]
description = '''
${mod_description}
'''
logoFile = "icon.png"
displayURL = "https://slimeymc.github.io/"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[40.1.69,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "valkyrienskies"
mandatory = true
versionRange = "[2.1.1-beta.1,)"
ordering = "AFTER"
side = "BOTH"